<?php

namespace Yoda\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getUpcomingEvents($max = null)
    {
        $dq = $this->createQueryBuilder('e')
        ->addOrderBy('e.time', 'ASC')
        ->andWhere('e.time > :now')
        ->setParameter('now', new \DateTime());

        if ($max) {
            $dq->setMaxResults($max);
        }

        return $dq
            ->getQuery()
            ->execute();
    }

    /**
     * @return Event[]
     */
    public function getRecentlyUpdatedEvents() {
        return $this->createQueryBuilder('e')
            ->andWhere('e.updatedAt > :since')
            ->setParameter('since', new \DateTime('24 hours ago'))
            ->getQuery()
            ->execute() ;
    }
}
